import { BaseItem } from '@/modules/items';

// In-memory data store for the template.
export let itemsDb: BaseItem[] = [
  {
    id: '1',
    creatorId: 'creator@gmail.com',
    creatorName: 'Neo Studio',
    createdAt: new Date().toISOString(),
    title: 'Ethereal Web Dashboard Kit',
    description: 'A complete SaaS reporting dashboard kit for Figma with 80+ components.',
    price: 39.00,
    category: 'ui-kit', 
    fileType: 'figma',
    previewImages: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80'],
    tags: ['saas', 'dashboard', 'figma']
  },
  {
    id: '2',
    creatorId: 'creator@gmail.com',
    creatorName: 'Zen Systems',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    title: 'Zen Productivity Planner',
    description: 'The ultimate minimalist Notion template for life management.',
    price: 19.00,
    category: 'template', 
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1616423640778-28d1b53229bd?w=800&q=80'],
    tags: ['notion', 'productivity', 'planner']
  },
  {
    id: '3',
    creatorId: 'systems@pro.net',
    creatorName: 'DevBoost',
    createdAt: new Date(Date.now() - 2*86400000).toISOString(),
    title: 'Next.js SaaS Boilerplate',
    description: 'Full-stack boilerplate with auth, payments, and dashboards.',
    price: 149.00,
    category: 'template', 
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80'],
    tags: ['react', 'nextjs', 'saas']
  },
  {
    id: '4',
    creatorId: 'art@design.com',
    creatorName: 'Violet Designs',
    createdAt: new Date(Date.now() - 5*86400000).toISOString(),
    title: '3D Abstract Shapes Pack',
    description: 'High-res abstract 3D shapes for modern brand identities.',
    price: 24.00,
    category: 'asset', 
    fileType: 'png',
    previewImages: ['https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=800&q=80'],
    tags: ['3d', 'abstract', 'assets']
  },
  {
    id: '5',
    creatorId: 'creator@gmail.com',
    creatorName: 'Neo Studio',
    createdAt: new Date(Date.now() - 6*86400000).toISOString(),
    title: 'Minimalist Icon Set',
    description: '1000+ vector icons in 3 styles for web and mobile.',
    price: 15.00,
    category: 'asset', 
    fileType: 'figma',
    previewImages: ['https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80'],
    tags: ['icons', 'figma', 'design']
  },
  {
    id: '6',
    creatorId: 'systems@pro.net',
    creatorName: 'DevBoost',
    createdAt: new Date(Date.now() - 7*86400000).toISOString(),
    title: 'Mastering React 18',
    description: 'A comprehensive deep dive into React 18 patterns.',
    price: 29.99,
    category: 'ebook', 
    fileType: 'pdf',
    previewImages: ['https://plus.unsplash.com/premium_photo-1683120974913-1ef17fbce24e?w=800&q=80'],
    tags: ['react', 'programming', 'education']
  },
  {
    id: '7',
    creatorId: 'creator@gmail.com',
    creatorName: 'Zen Systems',
    createdAt: new Date(Date.now() - 10*86400000).toISOString(),
    title: 'Ultimate Finance Tracker',
    description: 'Track income, expenses, and investments within Notion.',
    price: 12.00,
    category: 'template', 
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&q=80'],
    tags: ['notion', 'finance', 'tracker']
  },
  {
    id: '8',
    creatorId: 'art@design.com',
    creatorName: 'Violet Designs',
    createdAt: new Date(Date.now() - 15*86400000).toISOString(),
    title: 'Aurora Gradients Pack',
    description: 'Beautiful ambient gradients for web backgrounds.',
    price: 0.00,
    category: 'asset', 
    fileType: 'png',
    previewImages: ['https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=800&q=80'],
    tags: ['gradients', 'backgrounds', 'free']
  },
  {
    id: '9',
    creatorId: 'motion@visuals.net',
    creatorName: 'Flow Motion',
    createdAt: new Date(Date.now() - 18*86400000).toISOString(),
    title: 'Cinematic LUTS Bundle',
    description: 'Color grading presets for Premiere and Final Cut.',
    price: 49.00,
    category: 'asset', 
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&q=80'],
    tags: ['video', 'grading', 'luts']
  },
  {
    id: '10',
    creatorId: 'writer@words.com',
    creatorName: 'Jane Writer',
    createdAt: new Date(Date.now() - 20*86400000).toISOString(),
    title: 'Writing for Conversion',
    description: 'Copywriting secrets to triple your sales pages conversions.',
    price: 35.00,
    category: 'ebook', 
    fileType: 'pdf',
    previewImages: ['https://images.unsplash.com/photo-1455390582262-044cdead2708?w=800&q=80'],
    tags: ['marketing', 'copywriting', 'ebook']
  },
  {
    id: '11',
    creatorId: 'creator@gmail.com',
    creatorName: 'Neo Studio',
    createdAt: new Date(Date.now() - 25*86400000).toISOString(),
    title: 'Dark Mode Web Kit',
    description: 'Figma UI kit specializing strictly in dark mode interfaces.',
    price: 45.00,
    category: 'ui-kit', 
    fileType: 'figma',
    previewImages: ['https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=800&q=80'],
    tags: ['darkmode', 'figma', 'ui-kit']
  },
  {
    id: '12',
    creatorId: 'audio@studio.com',
    creatorName: 'Wave Audio',
    createdAt: new Date(Date.now() - 28*86400000).toISOString(),
    title: 'Lofi Beats Pack Vol. 1',
    description: 'Royalty free lofi beats for streaming and youtube.',
    price: 19.99,
    category: 'asset', 
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&q=80'],
    tags: ['audio', 'music', 'lofi']
  },
  {
    id: '13',
    creatorId: 'creator@gmail.com',
    creatorName: 'Zen Systems',
    createdAt: new Date(Date.now() - 30*86400000).toISOString(),
    title: 'Freelance CRM',
    description: 'Manage clients and invoices securely in Notion.',
    price: 25.00,
    category: 'template', 
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80'],
    tags: ['notion', 'freelance', 'crm']
  },
  {
    id: '14',
    creatorId: 'systems@pro.net',
    creatorName: 'DevBoost',
    createdAt: new Date(Date.now() - 35*86400000).toISOString(),
    title: 'Tailwind Components Library',
    description: 'A massive archive of copy-paste tailwind code blocks.',
    price: 69.00,
    category: 'template', 
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1555099962-4199c345e5dd?w=800&q=80'],
    tags: ['tailwind', 'css', 'react']
  },
  {
    id: '15',
    creatorId: 'art@design.com',
    creatorName: 'Violet Designs',
    createdAt: new Date(Date.now() - 40*86400000).toISOString(),
    title: 'Glassmorphism Vector Pack',
    description: 'Stunning glassmorphism assets for web layouts.',
    price: 10.00,
    category: 'asset', 
    fileType: 'png',
    previewImages: ['https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80'],
    tags: ['glassmorphism', 'vectors', 'abstract']
  },
  {
    id: '16',
    creatorId: 'writer@words.com',
    creatorName: 'Jane Writer',
    createdAt: new Date(Date.now() - 41*86400000).toISOString(),
    title: 'The Solopreneur Guide',
    description: 'How to build a one-person business from scratch.',
    price: 0.00,
    category: 'ebook', 
    fileType: 'pdf',
    previewImages: ['https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80'],
    tags: ['business', 'free', 'ebook']
  },
  {
    id: '17',
    creatorId: 'creator@gmail.com',
    creatorName: 'Neo Studio',
    createdAt: new Date(Date.now() - 45*86400000).toISOString(),
    title: 'Wireframing Kit 2.0',
    description: 'The fastest way to mock ideas in Figma.',
    price: 29.00,
    category: 'ui-kit', 
    fileType: 'figma',
    previewImages: ['https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&q=80'],
    tags: ['wireframe', 'figma', 'ui-kit']
  },
  {
    id: '18',
    creatorId: 'creator@gmail.com',
    creatorName: 'Zen Systems',
    createdAt: new Date(Date.now() - 50*86400000).toISOString(),
    title: 'Content Creator Planner',
    description: 'Schedule YouTube, TikTok, and Twitter from one template.',
    price: 15.00,
    category: 'template', 
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1542435503-956c469947f6?w=800&q=80'],
    tags: ['notion', 'social', 'planning']
  },
  {
    id: '19',
    creatorId: 'motion@visuals.net',
    creatorName: 'Flow Motion',
    createdAt: new Date(Date.now() - 55*86400000).toISOString(),
    title: 'Neon Transitions',
    description: 'Cyberpunk transition overlays for video editors.',
    price: 24.00,
    category: 'asset', 
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1563089145-599997674d42?w=800&q=80'],
    tags: ['neon', 'video', 'transitions']
  },
  {
    id: '20',
    creatorId: 'audio@studio.com',
    creatorName: 'Wave Audio',
    createdAt: new Date(Date.now() - 60*86400000).toISOString(),
    title: 'Cinematic Soundscapes',
    description: 'Epic background drones and risers.',
    price: 39.00,
    category: 'asset', 
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80'],
    tags: ['audio', 'cinematic', 'sounds']
  },
  {
    id: '21',
    creatorId: 'art@design.com',
    creatorName: 'Violet Designs',
    createdAt: new Date().toISOString(),
    title: 'Cyberpunk Icon Pack',
    description: 'High-quality neon icons for futuristic web projects.',
    price: 12.00,
    category: 'asset',
    fileType: 'png',
    previewImages: ['https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?w=800&q=80'],
    tags: ['cyberpunk', 'icons', 'neon']
  },
  {
    id: '22',
    creatorId: 'creator@gmail.com',
    creatorName: 'Neo Studio',
    createdAt: new Date().toISOString(),
    title: 'Fintech App UI Kit',
    description: 'A complete mobile application UI kit for banking and finance.',
    price: 59.00,
    category: 'ui-kit',
    fileType: 'figma',
    previewImages: ['https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80'],
    tags: ['fintech', 'app', 'figma']
  },
  {
    id: '23',
    creatorId: 'systems@pro.net',
    creatorName: 'DevBoost',
    createdAt: new Date().toISOString(),
    title: 'Kubernetes for Beginners',
    description: 'Learn the fundamentals of K8s orchestration in this ebook.',
    price: 25.00,
    category: 'ebook',
    fileType: 'pdf',
    previewImages: ['https://images.unsplash.com/photo-1667372393119-3d4410ED50D9?w=800&q=80'],
    tags: ['kubernetes', 'cloud', 'ebook']
  },
  {
    id: '24',
    creatorId: 'creator@gmail.com',
    creatorName: 'Zen Systems',
    createdAt: new Date().toISOString(),
    title: 'Social Media Management Hub',
    description: 'Notion dashboard for content scheduling and analytics.',
    price: 19.00,
    category: 'template',
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&q=80'],
    tags: ['notion', 'social', 'dashboard']
  },
  {
    id: '25',
    creatorId: 'motion@visuals.net',
    creatorName: 'Flow Motion',
    createdAt: new Date().toISOString(),
    title: 'Lo-fi Video Transitions',
    description: 'Vintage film grain and glitch effects for video editing.',
    price: 15.00,
    category: 'asset',
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1536240478700-b869070f9279?w=800&q=80'],
    tags: ['video', 'lofi', 'transitions']
  },
  {
    id: '26',
    creatorId: 'audio@studio.com',
    creatorName: 'Wave Audio',
    createdAt: new Date().toISOString(),
    title: 'Synthwave Drum Kit',
    description: 'Punchy 80s inspired drum samples for music producers.',
    price: 29.00,
    category: 'asset',
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1514320294323-261541be8604?w=800&q=80'],
    tags: ['audio', 'synthwave', 'drums']
  },
  {
    id: '27',
    creatorId: 'creator@gmail.com',
    creatorName: 'Neo Studio',
    createdAt: new Date().toISOString(),
    title: 'E-commerce Landing Page',
    description: 'High-converting Figma landing page design for digital stores.',
    price: 32.00,
    category: 'ui-kit',
    fileType: 'figma',
    previewImages: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80'],
    tags: ['ecommerce', 'landing-page', 'figma']
  },
  {
    id: '28',
    creatorId: 'writer@words.com',
    creatorName: 'Jane Writer',
    createdAt: new Date().toISOString(),
    title: 'SEO Writing Blueprint',
    description: 'Master the art of writing content that ranks on Google.',
    price: 45.00,
    category: 'ebook',
    fileType: 'pdf',
    previewImages: ['https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&q=80'],
    tags: ['seo', 'writing', 'marketing']
  },
  {
    id: '29',
    creatorId: 'creator@gmail.com',
    creatorName: 'Zen Systems',
    createdAt: new Date().toISOString(),
    title: 'Minimalist habit tracker',
    description: 'Simple and effective habit tracking Notion template.',
    price: 9.00,
    category: 'template',
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&q=80'],
    tags: ['notion', 'habits', 'productivity']
  },
  {
    id: '30',
    creatorId: 'systems@pro.net',
    creatorName: 'DevBoost',
    createdAt: new Date().toISOString(),
    title: 'Rust for Web Devs',
    description: 'Complete guide to building high-performance web apps with Rust.',
    price: 49.00,
    category: 'ebook',
    fileType: 'pdf',
    previewImages: ['https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&q=80'],
    tags: ['rust', 'webdev', 'ebook']
  },
  {
    id: '31',
    creatorId: 'art@design.com',
    creatorName: 'Violet Designs',
    createdAt: new Date().toISOString(),
    title: 'Pastel Gradient Pack',
    description: 'Soft and dreamy gradient backgrounds for modern designs.',
    price: 0.00,
    category: 'asset',
    fileType: 'png',
    previewImages: ['https://images.unsplash.com/photo-1557682250-33bd709cbe85?w=800&q=80'],
    tags: ['gradients', 'pastel', 'backgrounds']
  },
  {
    id: '32',
    creatorId: 'creator@gmail.com',
    creatorName: 'Neo Studio',
    createdAt: new Date().toISOString(),
    title: 'Crypto Dashboard UI',
    description: 'Advanced crypto portfolio tracker dashboard for Figma.',
    price: 49.00,
    category: 'ui-kit',
    fileType: 'figma',
    previewImages: ['https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=800&q=80'],
    tags: ['crypto', 'dashboard', 'figma']
  },
  {
    id: '33',
    creatorId: 'audio@studio.com',
    creatorName: 'Wave Audio',
    createdAt: new Date().toISOString(),
    title: 'Ambient Soundscape Vol 2',
    description: 'Deep and immersive atmospheric sounds for relaxation.',
    price: 24.00,
    category: 'asset',
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1493225255756-d9584f8606e9?w=800&q=80'],
    tags: ['audio', 'ambient', 'relaxation']
  },
  {
    id: '34',
    creatorId: 'creator@gmail.com',
    creatorName: 'Zen Systems',
    createdAt: new Date().toISOString(),
    title: 'Travel Planner Pro',
    description: 'Organize your trips, bookings, and budgets in Notion.',
    price: 15.00,
    category: 'template',
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80'],
    tags: ['notion', 'travel', 'planner']
  },
  {
    id: '35',
    creatorId: 'motion@visuals.net',
    creatorName: 'Flow Motion',
    createdAt: new Date().toISOString(),
    title: 'Glitch Effect Overlays',
    description: 'Dynamic glitch overlays for professional video production.',
    price: 19.00,
    category: 'asset',
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80'],
    tags: ['video', 'glitch', 'overlays']
  },
  {
    id: '36',
    creatorId: 'writer@words.com',
    creatorName: 'Jane Writer',
    createdAt: new Date().toISOString(),
    title: 'Freelance Business Bible',
    description: 'Everything you need to know to run a successful freelance business.',
    price: 39.00,
    category: 'ebook',
    fileType: 'pdf',
    previewImages: ['https://images.unsplash.com/photo-1454165833767-027ffea9e77b?w=800&q=80'],
    tags: ['freelance', 'business', 'ebook']
  },
  {
    id: '37',
    creatorId: 'creator@gmail.com',
    creatorName: 'Neo Studio',
    createdAt: new Date().toISOString(),
    title: 'Healthcare Mobile UI',
    description: 'Comprehensive mobile app design for doctors and patients.',
    price: 55.00,
    category: 'ui-kit',
    fileType: 'figma',
    previewImages: ['https://images.unsplash.com/photo-1576091160550-217359f42f8c?w=800&q=80'],
    tags: ['healthcare', 'app', 'figma']
  },
  {
    id: '38',
    creatorId: 'systems@pro.net',
    creatorName: 'DevBoost',
    createdAt: new Date().toISOString(),
    title: 'API Design Best Practices',
    description: 'A deep dive into creating robust and scalable APIs.',
    price: 29.00,
    category: 'ebook',
    fileType: 'pdf',
    previewImages: ['https://images.unsplash.com/photo-1516259762381-22954d7d3ad2?w=800&q=80'],
    tags: ['api', 'programming', 'ebook']
  },
  {
    id: '39',
    creatorId: 'creator@gmail.com',
    creatorName: 'Zen Systems',
    createdAt: new Date().toISOString(),
    title: 'Language Learning Dashboard',
    description: 'Track your progress and vocabulary in Notion.',
    price: 12.00,
    category: 'template',
    fileType: 'zip',
    previewImages: ['https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&q=80'],
    tags: ['notion', 'learning', 'language']
  },
  {
    id: '40',
    creatorId: 'art@design.com',
    creatorName: 'Violet Designs',
    createdAt: new Date().toISOString(),
    title: 'Retro Texture Pack',
    description: 'High-quality paper and film textures for authentic vintage looks.',
    price: 10.00,
    category: 'asset',
    fileType: 'png',
    previewImages: ['https://images.unsplash.com/photo-1550684376-efcbd6e3f031?w=800&q=80'],
    tags: ['textures', 'retro', 'vintage']
  }
];
